CREATE TABLE USER (
id VARCHAR(150) NOT NULL,
firstName VARCHAR(30) NULL,
lastName VARCHAR(30) NULL,
birthDate DATE,
PRIMARY KEY (id)
);

CREATE TABLE USER_INFO (
id VARCHAR(150) NOT NULL,
type VARCHAR(30) NULL,
text VARCHAR(120) NULL,
created TIMESTAMP
);

commit;